CREATE TABLE IF NOT EXISTS Professor
( PNr INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Name VARCHAR(256) );

CREATE TABLE IF NOT EXISTS Student
( MatrNr INTEGER UNSIGNED NOT NULL PRIMARY KEY,
Name VARCHAR(256) );

CREATE TABLE IF NOT EXISTS Lecture
( LNr INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
Title VARCHAR(256),
PNr INTEGER UNSIGNED NOT NULL REFERENCES Professor (PNr) );
CREATE TABLE IF NOT EXISTS Participation
( MatrNr INTEGER UNSIGNED NOT NULL REFERENCES Student (MatrNr),
LNr INTEGER UNSIGNED NOT NULL REFERENCES Lecture (LNr),
PRIMARY KEY (MatrNr,LNr) );






INSERT INTO Student (MatrNr, Name, City, MatrDate) VALUES
( 4711, ‘A‘, ‘Hamburg‘, DEFAULT),
( 4712, ‘B‘, ‘Berlin‘, ‘2019-09-02‘),
( 4713, ‘C‘, ‘Kiel‘, ‘2019-09-03‘);
INSERT INTO Professor (Name) VALUES
( ‘Michael‘ ), (‘Till‘);